header_path = -I/home/shang/code/C++/github/my-muduo/mymuduo/base -I/home/shang/code/C++/github/my-muduo/mymuduo/net
LIBS=-lpthread
CFLAGS= -g -Wall

test: test.cc
	g++ test.cc ${CFLAGS} ${header_path} ${LIBS}  -o test

clean:
	rm -r test

